#!/usr/bin/env python3
"""Generate the ignored Dart client configuration from process variables."""

from __future__ import annotations

import json
import os
from pathlib import Path


FIELDS = (
    ("supabaseUrl", "SUPABASE_URL"),
    ("supabaseAnonKey", "SUPABASE_ANON_KEY"),
    ("appleClientId", "APPLE_CLIENT_ID"),
    ("appleRedirectUri", "APPLE_REDIRECT_URI"),
    ("magicLaneApiKey", "MAGICLANE_API_KEY"),
    ("firebaseApiKey", "FIREBASE_API_KEY"),
    ("firebaseAppId", "FIREBASE_APP_ID"),
    ("firebaseMessagingSenderId", "FIREBASE_MESSAGING_SENDER_ID"),
    ("firebaseProjectId", "FIREBASE_PROJECT_ID"),
    ("firebaseStorageBucket", "FIREBASE_STORAGE_BUCKET"),
    ("firebaseIosBundleId", "FIREBASE_IOS_BUNDLE_ID"),
)


def dart_string(value: str) -> str:
    """Return a double-quoted Dart literal without interpolation."""
    return json.dumps(value).replace("$", r"\$")


def required(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def main() -> None:
    constants = "\n".join(
        f"  static const {dart_name} = {dart_string(required(env_name))};"
        for dart_name, env_name in FIELDS
    )
    output = f"""// Generated by scripts/generate_env_dart.py. Do not commit.
abstract final class Env {{
{constants}

  static bool get isConfigured =>
      _hasValue(supabaseUrl) && _hasValue(supabaseAnonKey);

  static bool get isFirebaseConfigured =>
      _hasValue(firebaseApiKey) &&
      _hasValue(firebaseAppId) &&
      _hasValue(firebaseMessagingSenderId) &&
      _hasValue(firebaseProjectId) &&
      _hasValue(firebaseStorageBucket) &&
      _hasValue(firebaseIosBundleId);

  static bool _hasValue(String value) =>
      value.isNotEmpty &&
      !value.contains('YOUR_') &&
      !value.startsWith('your_');
}}
"""
    target = Path("lib/core/config/env.dart")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(output, encoding="utf-8")


if __name__ == "__main__":
    main()
